import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import {
  ElasticAnimatableText,
  Button,
  Container,
  ProjectCard,
  BlogCard,
  Globe,
  Tendrils,
} from "../components";
import { useBreakpoints } from "../hooks";
import Section from "../layouts/Section";
const introHeading = ["Hi", "I'm Sherry,", "web developer"];
const Home: NextPage = () => {
  const { queryBreakpoints } = useBreakpoints();
  const canvasContainerRef = useRef(null);
  let radius = 400 / 1.5;
  if (queryBreakpoints("lg")) {
    radius = 300 / 1.5;
  }
  if (queryBreakpoints("xs")) {
    radius = 190 / 1.5;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Tendrils options={{}} />
        <section
          ref={canvasContainerRef}
          className="relative h-screen flex items-center"
        >
          <div className="inline-block text-left">
            {introHeading.map((val, i) => {
              return (
                <ElasticAnimatableText
                  key={i}
                  level={1}
                  text={val}
                  stagger
                  blockStagger
                  previousBlockSize={introHeading[i - 1]?.length || 0}
                />
              );
            })}

            <div className="mt-8">
              <p className="tracking-widest text-grey">
                Full Stack Developer / React Expert
              </p>
              <Button className=" mt-16">Contact Me</Button>
            </div>
          </div>
        </section>
        <Section title="About Me">
          <p className=" pt-16 pb-8">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime ab
            vero corrupti quam soluta cupiditate deleniti. Sapiente quae dolore
            fugiat. Modi cupiditate, consectetur quasi natus est fugit amet
            voluptate blanditiis.
          </p>
          {<Globe radius={radius} />}
        </Section>
        <Section title="My Projects">
          <ProjectCard />
          <ProjectCard reversed />
          <ProjectCard />
          <Button className="m-auto">See More</Button>
        </Section>
        <Section title="Blog Posts">
          <div className="grid grid-cols-1 sm:grid-cols-2 2xl:grid-cols-4 gap-10 py-16">
            <BlogCard></BlogCard>
            <BlogCard></BlogCard>
          </div>
          <Button className="m-auto">See More</Button>
        </Section>
        <Section title="Contact Me">
          <p className="py-16">
            I’m interested in freelance opportunities – especially ambitious or
            large projects. However, if you have other request or question,
            don’t hesitate to use the form.
          </p>
          <Button className="m-auto">Say Hello!</Button>
        </Section>
      </Container>
    </>
  );
};

export default Home;
